version: "3.8"

services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     args:
  #       BASE_IMAGE: ${BASE_IMAGE}
  #       # PROJECT_NAME: ${PROJECT_NAME}
  #   image: ${REPOSITORY_NAME}/${PROJECT_NAME}:latest
  #   ports:
  #     - "${PORT}:8000"
  #   environment:
  #     ENV: ${ENV}
  #     PREFIX: ${PREFIX}
  #     ROOT_PATH: ${ROOT_PATH}
  #     PORT: ${PORT}
  #     WORKERS: ${WORKERS}
  #     DB_TYPE: ${DB_TYPE}
  #     DB_USER: ${DB_USER}
  #     DB_PASSWORD: ${DB_PASSWORD}
  #     DB_HOST: ${DB_HOST}
  #     DB_PORT: ${DB_PORT}
  #     DB_NAME: ${DB_NAME}
  #     PROJECT_NAME: ${PROJECT_NAME}
  #   depends_on:
  #     - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - ./.helpers/volume/db_data:/var/lib/postgresql/data
