# Send message
POST http://0.0.0.0:8000/api/v1/twilio/send_message HTTP/1.1
Content-Type: application/json

{
    "recipient_number" : "+918340132212",
    "message" : "here we go again"
}

###

# Send poll

POST http://0.0.0.0:8000/api/v1/twilio/send_poll HTTP/1.1
Content-Type: application/json

{
    "recipient_number" : "+918340132212"
}


###

# receive poll

POST http://0.0.0.0:8000/api/v1/twilio/receive_message HTTP/1.1
Content-Type: application/json

{
    "recipient_number" : "+918340132212"
}